services:
  api:
    build: .
    container_name: api-ben10-iec
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ben10
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSL: 'false'
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: api-ben10-iec-db
    environment:
      POSTGRES_DB: ben10
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ben10']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: